# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_searchhistory_external_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='se_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
