# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170806_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalresource',
            name='update_interval',
            field=models.IntegerField(default=1),
        ),
    ]
