# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_externalresource_update_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalresource',
            old_name='url',
            new_name='_url',
        ),
        migrations.AddField(
            model_name='externalresource',
            name='hostname',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalresource',
            name='scheme',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalresource',
            name='se_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
