# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulatequeue',
            name='quick_ans',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
