# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggests', '0002_accumulatequeue_quick_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accumulatequeue',
            name='frequency',
        ),
        migrations.AddField(
            model_name='accumulatequeue',
            name='last',
            field=models.IntegerField(default=0),
        ),
    ]
