# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggests', '0006_auto_20170503_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulatequeue',
            name='group_id',
            field=models.CharField(max_length=14),
        ),
    ]
