# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_externalresourcesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalresource',
            name='_content_hash',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='externalresource',
            name='title',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
