# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170807_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalResourceSettings',
        ),
    ]
