# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_question_reindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('answer', 'id')},
        ),
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
