# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170130_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='external',
            field=models.BooleanField(default=False),
        ),
    ]
