# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_searchhistory_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='external_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.ExternalResource'),
        ),
    ]
