#!/bin/bash

echo -n "Database password: " && read -s PASSWORD && echo ""

sudo docker run --name postgresserver \
	-e POSTGRES_PASSWORD=$PASSWORD \
	-v qua-pgdata:/var/lib/postgresql/data \
	-p 5432:5432 \
	-d qua-postgres:latest
