#!/bin/bash

BUILD_DIR=docker_build
SERVICE_NAME=qua-ext

PASSWORD=$(qua-admin-keystore dbkey) \
	|| { echo "!! No database password specified"; exit; }

#
# CREATE BUILD DIRECTORY
#
echo "Creating docker build directory"

rm -rf $BUILD_DIR \
	&& mkdir $BUILD_DIR

ls | grep -v "$BUILD_DIR" | grep -v build | \
while read line;
	do cp -r $line $BUILD_DIR/;
done

cd $BUILD_DIR


#
# DELETE PYC AND CACHE
#
echo "Delete cache files"

find . -name "*.pyc" | \
while read line;
	do rm -f $line;
done

find . -name "*pycache*" | \
while read line;
	do rm -rf $line;
done


#
# SET DJANGO KEY AND DEGUG = FALSE
#
echo "Set django key and debug = False"

sed -i "s/DEBUG = True/DEBUG = False/g" src/app/settings.py
sed -i "s/somestrongdjangokey/$(qua-admin-keystore djangokey)/g" src/app/settings.py


#
# BUILD DOCKER IMAGE
#
echo "Start building docker image"

sudo docker build -t $SERVICE_NAME:latest .


#
# TAKE OUT THE GARBAGE
#
echo "Cleaning..."

cd .. && rm -rf $BUILD_DIR
