#!/bin/bash

sudo docker run -d \
	--name qua-ext \
	--link postgresserver:postgresserver \
	--link redisserver:redisserver \
	--link qua-search:qua-search \
	-v qua-ext-data:/var/lib/qua/data \
	-p 9000:80 \
	qua-ext:latest
