#!/bin/bash

sudo docker run -d \
	--name qua-controller \
	--link postgresserver:postgresserver \
	--link redisserver:redisserver \
	--link qua-search:qua-search \
	-v qua-controller-data:/var/lib/qua/data \
	-p 9000:80 \
	qua-controller:latest
