#!/bin/bash

BUILD_DIR=docker_build

echo -n "Database password: " && read -s PASSWORD && echo ""

#
# CREATE BUILD DIRECTORY
#
echo "Creating docker build directory"

rm -rf $BUILD_DIR \
	&& mkdir $BUILD_DIR

ls | grep -v "$BUILD_DIR" | grep -v build | \
while read line;
	do cp -r $line $BUILD_DIR/;
done

cd $BUILD_DIR


#
# PREPARE QUA COMMON LIBRARY
#
echo "Prepare qua common library"

mkdir qua_common && \
	cp -r ../../common/* qua_common/ \
	&& cd qua_common

sed -i "s/somestrongdbpassword/$PASSWORD/g" qua/settings.py \
	&& cd ..


#
# DELETE PYC AND CACHE
#
echo "Delete cache files"

find . -name "*.pyc" | \
while read line;
	do rm -f $line;
done

find . -name "*pycache*" | \
while read line;
	do rm -rf $line;
done


#
# SET DJANGO KEY AND DEGUG = FALSE
#
echo "Set django key and debug = False"

sed -i "s/DEBUG = True/DEBUG = False/g" src/app/settings.py
sed -i "s/somestrongdjangokey/$(qua-admin-keygen)/g" src/app/settings.py


#
# BUILD DOCKER IMAGE
#
echo "Start building docker image"

sudo docker build -t qua-api:latest .


#
# TAKE OUT THE GARBAGE
#
echo "Cleaning..."

cd .. && rm -rf $BUILD_DIR
